### ISSUE TITLE
Poetry installation fails

### ISSUE THREAD

**Issue by Niko-ZeroG** [CRitter93/beehyve#6]
The installation of beehyve with poetry fails.

When running:
poetry add git+https://github.com/CRitter93/beehyve.git

The result is:
Updating dependencies
Resolving dependencies... (1.0s)

  CalledProcessError

  Command '['git', '--git-dir', '/var/folders/zd/8krh88mx4nx6_61djhpzw_fsxn2b21/T/pypoetry-git-beehyvedi22ddcv/.git', '--work-tree', '/var/folders/zd/8krh88mx4nx6_61djhpzw_fsxn2b21/T/pypoetry-git-beehyvedi22ddcv', 'checkout', 'master']' returned non-zero exit status 1.

  at ~/.poetry/lib/poetry/utils/_compat.py:217 in run
      213│                 process.wait()
      214│                 raise
      215│             retcode = process.poll()
      216│             if check and retcode:
    → 217│                 raise CalledProcessError(
      218│                     retcode, process.args, output=stdout, stderr=stderr
      219│                 )
      220│         finally:
      221│             # None because our context manager __exit__ does not use them.

**Comment by CRitter93** [comment]
Hey,

the issues arises from poetry trying to check out the `master` branch (which is the default branch used by poetry), but this repository uses a `main` branch (according to [Link](https://github.blog/changelog/2020-10-01-the-default-branch-for-newly-created-repositories-is-now-main/)).

To use this branch in poetry, use:

```bash
poetry add git+https://github.com/CRitter93/beehyve.git#main
```

**Comment by Niko-ZeroG** [comment]
Awesome, thank you for the quick help :-)
Works like a charm now!
